name: notion_dashboard
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^6.0.5
  bloc: ^8.1.1
  chopper: ^6.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  widgets_to_image: ^0.0.2

dev_dependencies:
  auto_route_generator: ^6.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
